---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hubin.
--- DateTime: 2019/8/20 上午11:23
---

-- function ItemUsageThink()
--     return
-- end

--function AbilityUsageThink()
--    return
--end

-- function CourierUsageThink()
--     return
-- end

-- function BuybackUsageThink()
--     return
-- end

--function AbilityLevelUpThink()
--    return
--end
