---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hubin.
--- DateTime: 19-1-25 下午2:49
---

local UseCourier = {}

UseCourier.Name = "Use Courier Action"
UseCourier.NumArgs = 2

function UseCourier:Call(bot, actionType)
    if GetNumCouriers() == 0 then return end
    if bot:IsIllusion() then return end
    local courier = nil
    for i = 0, GetNumCouriers() do
        local t = GetCourier(i)
        if bot:GetPlayerID() == t:GetPlayerID() then
            courier = t
            break
        end
    end

    if courier == nil then return end

    local state = GetCourierState(courier)

    if state == COURIER_STATE_DEAD or courier:GetHealth() < 1 then
        return
    else
        bot:ActionImmediate_Courier(courier, actionType[1])
    end

end

return UseCourier
